version: '3.9'
services:

  core:
    build:
      context: core
    container_name: core
    restart: always
    volumes:
      - ./core/src:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./.env
    depends_on:
      - db
      - traefik
    ports:
      - 5000:5000
    labels:
      # - "traefik.enable=true"
      - "traefik.http.routers.core.rule=Host(`app.localhost`)"
      - "traefik.http.services.core.loadbalancer.server.port=5000"
      # - "traefik.http.routers.core.entrypoints=web"
    networks:
      - backnet
      - frontnet
      
  worker:
    build:
      context: core
    container_name: worker
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./core/src:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./.env
    depends_on:
      - core
      - redis
    networks:
      - backnet

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backnet

  traefik:
    image: "traefik:2.9"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entrypoints.web.address=:80"
      # - "--providers.docker.network=arceus-frontnet"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - frontnet
    

  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backnet

  admin:
    image: phpmyadmin
    container_name: admin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 8090:80
    networks:
      - backnet
    
volumes:
  mariadb_data:
networks:
  backnet:
  frontnet:
  test:
