version: '3.9'
services:
  core:
    build:
      context: core
    container_name: core
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./core/src:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./.env
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backnet
  admin:
    image: phpmyadmin
    container_name: admin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    networks:
      - backnet

volumes:
  mariadb_data:
networks:
  backnet:
  frontnet: