"""empty message

Revision ID: 87f57c70d0a0
Revises: a11c05194817
Create Date: 2023-05-17 22:32:02.266131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87f57c70d0a0'
down_revision = 'a11c05194817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
