"""empty message

Revision ID: a11c05194817
Revises: a150d3e47998
Create Date: 2023-05-16 15:56:53.266434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11c05194817'
down_revision = 'a150d3e47998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pers_datos', sa.Boolean(), nullable=True),
    sa.Column('so', sa.Enum('Kali', 'Ubuntu', 'Fedora', name='so'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm')
    # ### end Alembic commands ###
